### ISSUE TITLE
"AttributeError: 'NoneType' object has no attribute 'find'"

### ISSUE THREAD

**Issue by Shazgul** [Pure-L0G1C/SQL-scanner#3]
```
[*] Dork: streamer.php?id=
[i] Starting daemon threads ...
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/content/SQL-scanner/lib/search.py", line 77, in start
    self.find_links()
  File "/content/SQL-scanner/lib/search.py", line 51, in find_links
    a = r.find('h2', first=True).find('a', first=True)
AttributeError: 'NoneType' object has no attribute 'find'
```

Getting this Error while searching for "streamer.php?id=", also "liga.php?id=" gives no output.

**Comment by ghost** [comment]
'  '    <---- thats your problem

**Comment by bns34** [comment]
> ' ' <---- thats your problem

that literally doesnt help

**Comment by bns34** [comment]
> ' ' <---- thats your problem

no contents of html.find('.b_algo')?

**Comment by ghost** [comment]
> > ' ' <---- thats your problem
> 
> no contents of html.find('.b_algo')?

I ran it without them and its working 100%% 
Would you like a Screenshot of proof ??
[i] Starting vulnerability scanner ...

**Comment by ghost** [comment]
also my guess is he is a little newer to Dorking Tools which is okay we all start off somewhere but should learn how to write your dorks the correct way to ever achieve anything worth while

**Comment by bns34** [comment]
> > > ' ' <---- thats your problem
> 
> > 
> 
> > no contents of html.find('.b_algo')?
> 
> 
> 
> I ran it without them and its working 100%% 
> 
> Would you like a Screenshot of proof ??
> 
> [i] Starting vulnerability scanner ...
> 
> 

You ran it without what? The search.py file?
